# Set to false to create a new comment instead of updating the app's first one
updateComment: true

# Use a custom string, or set to false to disable
before: false

# Use a custom string, or set to false to disable
after: false
