# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: circleci/python:2.7.14

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: /home/circleci/hello-world

    steps:
      - checkout
 
      # run tests!
      # this example uses Django's built-in test-runner
      # other common Python testing frameworks include pytest and nose
      # https://pytest.org
      # https://nose.readthedocs.io
      - run:
          name: run file
          command: |
            python ex.py
      - run:
          name: run tests
          command: |
            sudo pip install coverage
            coverage run ex.py
           
      - run:
          name: Generate backend coverage report
          command: |
            sudo pip install codecov
            codecov
          when: on_success

      - store_artifacts:
          path: test-reports
          destination: test-reports
